"""
Level Up Pipeline Health Monitor -- Meta-DAG.

This DAG runs daily at 06:00 UTC, after the data pipeline (02:00 UTC) and
ML pipeline (04:00 UTC) have both had time to complete.  It performs
end-to-end health checks across the entire Level Up platform:

  t1  check_data_pipeline   -- verify data pipeline outputs exist and are fresh
  t2  check_ml_pipeline     -- verify ML model exists and validation passed
  t3  check_data_freshness  -- verify processed data is not stale (< 48 h old)
  t4  check_model_quality   -- read validation_report.json, enforce MAE/R2 thresholds
  t5  check_bias_report     -- verify no critical bias flags in bias_detection_report.json
  t6  generate_health_report -- aggregate all check results into pipeline_health.json
  t7  alert_on_issues       -- send a Slack alert if any upstream check failed

Each check task pushes a dict to XCom with the shape:
    {"status": "PASS"|"FAIL", "details": "..."}
so that downstream tasks can aggregate results without re-reading files.

Design principles:
    - Defensive: every check handles missing files gracefully and reports what
      is wrong rather than crashing the entire DAG.
    - Observable: the health report JSON is a single file an on-call engineer
      can curl/open to see overall pipeline status at a glance.
    - Actionable: the Slack alert task only fires when something actually needs
      attention, keeping alert fatigue low.
"""

from datetime import datetime, timedelta
import json
import os
from pathlib import Path

from airflow import DAG
from airflow.operators.python import PythonOperator

# ---------------------------------------------------------------------------
# Path constants -- derived from the repo layout so the DAG stays portable.
# The DAG file lives at  Data-Pipeline/dags/levelup_pipeline_monitor.py
# ---------------------------------------------------------------------------

_DAG_DIR = Path(__file__).resolve().parent                      # .../Data-Pipeline/dags
_DATA_PIPELINE_DIR = _DAG_DIR.parent                            # .../Data-Pipeline
_REPO_ROOT = _DATA_PIPELINE_DIR.parent                          # .../levelup-1
_ML_PIPELINE_DIR = _REPO_ROOT / "ML-Pipeline"

# -- Data-Pipeline artefacts --
_PROCESSED_DIR = _DATA_PIPELINE_DIR / "data" / "processed"
_REPORTS_DIR = _DATA_PIPELINE_DIR / "data" / "reports"

# Core processed outputs from the data pipeline
_DATA_PIPELINE_OUTPUTS = {
    "sleep_daily":  _PROCESSED_DIR / "sleep_daily.parquet",
    "int_daily":    _PROCESSED_DIR / "int_daily.parquet",
    "daily_joined": _PROCESSED_DIR / "daily_joined.parquet",
}

# Reports generated by the data pipeline
_DATA_PIPELINE_REPORTS = {
    "schema":  _REPORTS_DIR / "schema.json",
    "stats":   _REPORTS_DIR / "stats.json",
}

# -- ML-Pipeline artefacts --
_MODELS_DIR = _ML_PIPELINE_DIR / "models"
_ML_REPORTS_DIR = _ML_PIPELINE_DIR / "reports"

_BEST_MODEL_PATH = _MODELS_DIR / "best_model.joblib"
_VALIDATION_REPORT = _ML_REPORTS_DIR / "validation_report.json"
_BIAS_DETECTION_REPORT = _ML_REPORTS_DIR / "bias_detection_report.json"

# -- Health report output --
_HEALTH_REPORT_PATH = _REPORTS_DIR / "pipeline_health.json"

# -- Quality thresholds (must stay in sync with ML-Pipeline/config.py) --
_MAX_ACCEPTABLE_MAE = 5.0
_MIN_ACCEPTABLE_R2 = 0.7

# -- Freshness window: data older than this is considered stale --
_FRESHNESS_HOURS = 48

# -- Slack webhook (read from env so secrets stay out of code) --
_SLACK_WEBHOOK_URL = os.environ.get("LEVELUP_SLACK_WEBHOOK_URL", "")


# ===========================================================================
# Helper utilities
# ===========================================================================

def _file_age_hours(path: Path) -> float | None:
    """Return the age of *path* in hours, or None if the file does not exist."""
    try:
        mtime = path.stat().st_mtime
        age_seconds = datetime.now().timestamp() - mtime
        return age_seconds / 3600.0
    except (FileNotFoundError, OSError):
        return None


def _read_json(path: Path) -> dict | None:
    """Safely read and parse a JSON file.  Returns None on any error."""
    try:
        return json.loads(path.read_text())
    except (FileNotFoundError, OSError, json.JSONDecodeError):
        return None


# ===========================================================================
# Task callables
# ===========================================================================

def check_data_pipeline(**context):
    """
    t1 -- Verify that the data pipeline produced its expected output files
    and that the core reports exist.

    Checks:
        - sleep_daily.parquet, int_daily.parquet, daily_joined.parquet exist
        - schema.json and stats.json reports exist
    """
    missing_outputs = []
    for name, path in _DATA_PIPELINE_OUTPUTS.items():
        if not path.exists():
            missing_outputs.append(name)

    missing_reports = []
    for name, path in _DATA_PIPELINE_REPORTS.items():
        if not path.exists():
            missing_reports.append(name)

    all_missing = missing_outputs + missing_reports

    if all_missing:
        result = {
            "status": "FAIL",
            "details": (
                f"Missing data-pipeline artefacts: {', '.join(all_missing)}. "
                "The data pipeline may not have run or completed successfully."
            ),
        }
    else:
        result = {
            "status": "PASS",
            "details": (
                "All data-pipeline outputs present: "
                f"{list(_DATA_PIPELINE_OUTPUTS.keys())} and reports "
                f"{list(_DATA_PIPELINE_REPORTS.keys())}."
            ),
        }

    # Push result to XCom so downstream tasks can read it
    context["ti"].xcom_push(key="check_result", value=result)
    print(f"[check_data_pipeline] {result['status']}: {result['details']}")
    return result


def check_ml_pipeline(**context):
    """
    t2 -- Verify that the ML pipeline produced a trained model and that
    the validation report indicates a passing status.

    Checks:
        - best_model.joblib exists
        - validation_report.json exists and has status == "PASS"
    """
    issues = []

    # Check model file
    if not _BEST_MODEL_PATH.exists():
        issues.append("best_model.joblib not found")

    # Check validation report existence and top-level status
    report = _read_json(_VALIDATION_REPORT)
    if report is None:
        issues.append("validation_report.json missing or unreadable")
    elif report.get("status") != "PASS":
        issues.append(
            f"validation_report.json status is '{report.get('status', 'UNKNOWN')}' (expected PASS)"
        )

    if issues:
        result = {
            "status": "FAIL",
            "details": "ML pipeline issues: " + "; ".join(issues),
        }
    else:
        result = {
            "status": "PASS",
            "details": "ML model exists and validation report status is PASS.",
        }

    context["ti"].xcom_push(key="check_result", value=result)
    print(f"[check_ml_pipeline] {result['status']}: {result['details']}")
    return result


def check_data_freshness(**context):
    """
    t3 -- Verify that processed data files were written recently enough
    to be considered current.

    A file is "stale" if its modification time is older than
    _FRESHNESS_HOURS (default 48 h).  This catches scenarios where the
    data pipeline silently skipped re-processing.
    """
    stale = []
    missing = []

    for name, path in _DATA_PIPELINE_OUTPUTS.items():
        age = _file_age_hours(path)
        if age is None:
            missing.append(name)
        elif age > _FRESHNESS_HOURS:
            stale.append(f"{name} ({age:.1f} h old)")

    problems = []
    if missing:
        problems.append(f"Missing files: {', '.join(missing)}")
    if stale:
        problems.append(
            f"Stale files (>{_FRESHNESS_HOURS}h): {', '.join(stale)}"
        )

    if problems:
        result = {
            "status": "FAIL",
            "details": "Data freshness issues: " + "; ".join(problems),
        }
    else:
        # Include the actual ages for observability
        ages = {
            name: f"{_file_age_hours(path):.1f}h"
            for name, path in _DATA_PIPELINE_OUTPUTS.items()
        }
        result = {
            "status": "PASS",
            "details": f"All processed data within {_FRESHNESS_HOURS}h window. Ages: {ages}",
        }

    context["ti"].xcom_push(key="check_result", value=result)
    print(f"[check_data_freshness] {result['status']}: {result['details']}")
    return result


def check_model_quality(**context):
    """
    t4 -- Read validation_report.json and enforce MAE / R-squared thresholds.

    This is a deeper check than t2 (which only looks at the report's own
    status field).  Here we independently verify the metric values against
    our thresholds, guarding against a report that says PASS but contains
    metrics that have drifted outside acceptable bounds.
    """
    report = _read_json(_VALIDATION_REPORT)

    if report is None:
        result = {
            "status": "FAIL",
            "details": "validation_report.json is missing or cannot be parsed.",
        }
        context["ti"].xcom_push(key="check_result", value=result)
        print(f"[check_model_quality] {result['status']}: {result['details']}")
        return result

    metrics = report.get("metrics", {})
    mae = metrics.get("mae")
    r2 = metrics.get("r2")

    issues = []

    # Validate MAE
    if mae is None:
        issues.append("MAE metric missing from report")
    elif mae > _MAX_ACCEPTABLE_MAE:
        issues.append(
            f"MAE {mae:.4f} exceeds threshold {_MAX_ACCEPTABLE_MAE}"
        )

    # Validate R-squared
    if r2 is None:
        issues.append("R2 metric missing from report")
    elif r2 < _MIN_ACCEPTABLE_R2:
        issues.append(
            f"R2 {r2:.4f} below threshold {_MIN_ACCEPTABLE_R2}"
        )

    if issues:
        result = {
            "status": "FAIL",
            "details": "Model quality issues: " + "; ".join(issues),
        }
    else:
        result = {
            "status": "PASS",
            "details": (
                f"Model quality OK -- MAE={mae:.4f} (<={_MAX_ACCEPTABLE_MAE}), "
                f"R2={r2:.4f} (>={_MIN_ACCEPTABLE_R2})."
            ),
        }

    context["ti"].xcom_push(key="check_result", value=result)
    print(f"[check_model_quality] {result['status']}: {result['details']}")
    return result


def check_bias_report(**context):
    """
    t5 -- Verify that the bias detection report has no critical flags.

    The ML-Pipeline bias_detection_report.json contains a "flagged_slices"
    list.  Any non-empty list means at least one demographic slice showed
    a MAE deviation > 20 % from the global MAE -- a potential fairness risk.
    """
    report = _read_json(_BIAS_DETECTION_REPORT)

    if report is None:
        result = {
            "status": "FAIL",
            "details": "bias_detection_report.json is missing or cannot be parsed.",
        }
        context["ti"].xcom_push(key="check_result", value=result)
        print(f"[check_bias_report] {result['status']}: {result['details']}")
        return result

    flagged = report.get("flagged_slices", [])

    if flagged:
        result = {
            "status": "FAIL",
            "details": (
                f"{len(flagged)} bias-flagged slice(s): {', '.join(flagged)}. "
                "Review bias_detection_report.json and consider mitigation steps."
            ),
        }
    else:
        total_samples = report.get("total_samples", "?")
        global_mae = report.get("global_mae", "?")
        result = {
            "status": "PASS",
            "details": (
                f"No bias flags. Global MAE={global_mae}, "
                f"total_samples={total_samples}."
            ),
        }

    context["ti"].xcom_push(key="check_result", value=result)
    print(f"[check_bias_report] {result['status']}: {result['details']}")
    return result


def generate_health_report(**context):
    """
    t6 -- Aggregate all upstream check results into a single
    pipeline_health.json file.

    The report includes:
        - overall_status: HEALTHY if all checks passed, DEGRADED otherwise
        - timestamp of this run
        - per-check status and detail strings
        - list of failed checks for quick triage
    """
    ti = context["ti"]

    # Collect XCom results from every upstream check task
    check_task_ids = [
        "check_data_pipeline",
        "check_ml_pipeline",
        "check_data_freshness",
        "check_model_quality",
        "check_bias_report",
    ]

    checks = {}
    failed_checks = []

    for task_id in check_task_ids:
        result = ti.xcom_pull(task_ids=task_id, key="check_result")
        if result is None:
            # This should not happen in normal operation, but handle it
            # defensively in case an upstream task was skipped or errored
            # before pushing to XCom.
            result = {
                "status": "FAIL",
                "details": f"No XCom result received from {task_id} (task may have been skipped or crashed).",
            }
        checks[task_id] = result
        if result["status"] != "PASS":
            failed_checks.append(task_id)

    overall_status = "HEALTHY" if not failed_checks else "DEGRADED"

    health_report = {
        "overall_status": overall_status,
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "checks": checks,
        "failed_checks": failed_checks,
        "total_checks": len(check_task_ids),
        "passed_checks": len(check_task_ids) - len(failed_checks),
    }

    # Ensure the reports directory exists
    _HEALTH_REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)

    _HEALTH_REPORT_PATH.write_text(json.dumps(health_report, indent=2))
    print(f"[generate_health_report] Written to {_HEALTH_REPORT_PATH}")
    print(f"[generate_health_report] Overall status: {overall_status}")

    if failed_checks:
        print(f"[generate_health_report] Failed checks: {failed_checks}")

    # Push the report dict itself so the alert task can consume it directly
    ti.xcom_push(key="health_report", value=health_report)

    return health_report


def alert_on_issues(**context):
    """
    t7 -- Send a Slack alert if any upstream health check failed.

    Behaviour:
        - If overall_status is HEALTHY, log a short "all clear" and return.
        - If overall_status is DEGRADED, build a Slack message summarizing
          which checks failed and POST it to the configured webhook URL.
        - If the webhook URL is not configured, log a warning but do NOT
          fail the task -- we still want the DAG to succeed so the health
          report is available.
    """
    ti = context["ti"]
    health_report = ti.xcom_pull(task_ids="generate_health_report", key="health_report")

    if health_report is None:
        print("[alert_on_issues] WARNING: No health report found in XCom. Cannot evaluate alert.")
        return

    overall = health_report.get("overall_status", "UNKNOWN")

    # ----- Happy path: nothing to do -----
    if overall == "HEALTHY":
        print("[alert_on_issues] All pipeline checks passed. No alert needed.")
        return

    # ----- Build alert message -----
    failed = health_report.get("failed_checks", [])
    checks = health_report.get("checks", {})
    passed = health_report.get("passed_checks", 0)
    total = health_report.get("total_checks", 0)

    lines = [
        "*Level Up Pipeline Health Alert*",
        f"Status: *{overall}*  |  {passed}/{total} checks passed",
        "",
        "*Failed checks:*",
    ]

    for task_id in failed:
        detail = checks.get(task_id, {}).get("details", "no details")
        lines.append(f"  - `{task_id}`: {detail}")

    lines.append("")
    lines.append(
        f"_Health report: {_HEALTH_REPORT_PATH}_  |  "
        f"_Timestamp: {health_report.get('timestamp', 'N/A')}_"
    )

    message = "\n".join(lines)
    print(f"[alert_on_issues] Alert message:\n{message}")

    # ----- Send to Slack -----
    if not _SLACK_WEBHOOK_URL:
        print(
            "[alert_on_issues] WARNING: LEVELUP_SLACK_WEBHOOK_URL is not set. "
            "Slack alert was NOT sent. Set the env var to enable notifications."
        )
        return

    # Use urllib so we have zero extra dependencies beyond the standard library
    import urllib.request

    payload = json.dumps({"text": message}).encode("utf-8")
    req = urllib.request.Request(
        _SLACK_WEBHOOK_URL,
        data=payload,
        headers={"Content-Type": "application/json"},
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            print(f"[alert_on_issues] Slack responded {resp.status}")
    except Exception as exc:
        # Log but do NOT fail the DAG -- alerting is best-effort.
        print(f"[alert_on_issues] WARNING: Slack POST failed: {exc}")


# ===========================================================================
# DAG definition
# ===========================================================================

default_args = {
    "owner": "levelup",
    "depends_on_past": False,
    "email_on_failure": False,
    "retries": 1,
    "retry_delay": timedelta(minutes=3),
}

with DAG(
    dag_id="levelup_pipeline_monitor",
    default_args=default_args,
    description=(
        "Meta-DAG that verifies the data pipeline and ML pipeline both "
        "completed successfully and produced valid, fresh artefacts."
    ),
    schedule_interval="0 6 * * *",       # daily at 06:00 UTC
    start_date=datetime(2025, 1, 1),
    catchup=False,
    tags=["levelup", "mlops", "monitoring", "meta-dag"],
) as dag:

    # -- t1: verify data pipeline outputs --
    t1 = PythonOperator(
        task_id="check_data_pipeline",
        python_callable=check_data_pipeline,
    )

    # -- t2: verify ML model + validation status --
    t2 = PythonOperator(
        task_id="check_ml_pipeline",
        python_callable=check_ml_pipeline,
    )

    # -- t3: verify processed data is not stale --
    t3 = PythonOperator(
        task_id="check_data_freshness",
        python_callable=check_data_freshness,
    )

    # -- t4: independently verify MAE / R2 thresholds --
    t4 = PythonOperator(
        task_id="check_model_quality",
        python_callable=check_model_quality,
    )

    # -- t5: verify no critical bias flags --
    t5 = PythonOperator(
        task_id="check_bias_report",
        python_callable=check_bias_report,
    )

    # -- t6: aggregate results into pipeline_health.json --
    t6 = PythonOperator(
        task_id="generate_health_report",
        python_callable=generate_health_report,
    )

    # -- t7: send Slack alert if anything failed --
    t7 = PythonOperator(
        task_id="alert_on_issues",
        python_callable=alert_on_issues,
    )

    # -- Linear dependency chain --
    t1 >> t2 >> t3 >> t4 >> t5 >> t6 >> t7
